[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/era-contracts/l1-contracts/node_modules/@openzeppelin/",
    "ds-test/=lib/usdc-token/lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/usdc-token/lib/forge-std/src/",
    "usdc-token/=lib/usdc-token/",
    "l1-contracts/=lib/era-contracts/l1-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
