[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/usdc-token/node_modules/@openzeppelin/",
    "ds-test/=lib/usdc-token/lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/usdc-token/lib/forge-std/src/",
    "usdc-token/=lib/usdc-token/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
